import type { Issue, StatusUpdate } from "./types"

export const mockIssues: Issue[] = [
  {
    id: "1",
    title: "Large pothole on Main Street",
    description: "Deep pothole causing traffic issues near the market area",
    category: "pothole",
    status: "in-progress",
    priority: "high",
    location: {
      lat: 23.3441,
      lng: 85.3096,
      address: "Main Street, Ranchi, Jharkhand",
    },
    photos: ["/pothole-on-road.jpg"],
    citizenName: "Rajesh Kumar",
    citizenPhone: "+91 98765 43210",
    citizenEmail: "rajesh@example.com",
    department: "roads",
    assignedTo: "Amit Singh",
    createdAt: new Date("2025-01-02"),
    updatedAt: new Date("2025-01-04"),
  },
  {
    id: "2",
    title: "Streetlight not working",
    description: "Street light has been out for 3 days, creating safety concerns",
    category: "streetlight",
    status: "assigned",
    priority: "medium",
    location: {
      lat: 23.3571,
      lng: 85.335,
      address: "Park Road, Ranchi, Jharkhand",
    },
    photos: ["/broken-streetlight-night.png"],
    citizenName: "Priya Sharma",
    citizenPhone: "+91 98765 43211",
    citizenEmail: "priya@example.com",
    department: "electricity",
    assignedTo: "Vikram Rao",
    createdAt: new Date("2025-01-03"),
    updatedAt: new Date("2025-01-03"),
  },
  {
    id: "3",
    title: "Garbage pile near residential area",
    description: "Uncollected garbage for over a week, causing health hazards",
    category: "garbage",
    status: "resolved",
    priority: "critical",
    location: {
      lat: 23.3629,
      lng: 85.3346,
      address: "Gandhi Nagar, Ranchi, Jharkhand",
    },
    photos: ["/garbage-pile-on-street.jpg"],
    citizenName: "Sunita Devi",
    citizenPhone: "+91 98765 43212",
    citizenEmail: "sunita@example.com",
    department: "sanitation",
    assignedTo: "Ramesh Gupta",
    createdAt: new Date("2024-12-28"),
    updatedAt: new Date("2025-01-05"),
    resolvedAt: new Date("2025-01-05"),
  },
  {
    id: "4",
    title: "Water leakage from main pipe",
    description: "Continuous water leakage wasting water and damaging road",
    category: "water",
    status: "under-review",
    priority: "high",
    location: {
      lat: 23.352,
      lng: 85.324,
      address: "Station Road, Ranchi, Jharkhand",
    },
    photos: ["/water-pipe-leakage-on-street.jpg"],
    citizenName: "Anil Verma",
    citizenPhone: "+91 98765 43213",
    citizenEmail: "anil@example.com",
    department: "water-supply",
    createdAt: new Date("2025-01-05"),
    updatedAt: new Date("2025-01-05"),
  },
  {
    id: "5",
    title: "Blocked drainage causing flooding",
    description: "Drainage blocked with debris, water accumulating during rain",
    category: "drainage",
    status: "submitted",
    priority: "medium",
    location: {
      lat: 23.348,
      lng: 85.318,
      address: "College Road, Ranchi, Jharkhand",
    },
    photos: ["/blocked-drainage-with-water.jpg"],
    citizenName: "Meera Patel",
    citizenPhone: "+91 98765 43214",
    citizenEmail: "meera@example.com",
    createdAt: new Date("2025-01-06"),
    updatedAt: new Date("2025-01-06"),
  },
]

export const mockStatusUpdates: StatusUpdate[] = [
  {
    id: "1",
    issueId: "1",
    status: "in-progress",
    message: "Work crew dispatched to location",
    updatedBy: "Amit Singh",
    timestamp: new Date("2025-01-04"),
  },
  {
    id: "2",
    issueId: "3",
    status: "resolved",
    message: "Garbage collected and area cleaned",
    updatedBy: "Ramesh Gupta",
    timestamp: new Date("2025-01-05"),
  },
]
